export const user=[
    {  
        id:1, 
        name:"Aram",
        lastname:"Gevorgyan",
        age:25,
        email:"AramGevorgyan@mail.ru",
        city:"Gyumri"
    },
    {
        id:2,
        name:"Maikl",
        lastname:"Jekson",
        age:34,
        email:"MaiklJekson@mail.ru",
        city:"Franc"
    },
    {
        id:3,
        name:"jon",
        lastname:"Smit",
        age:23,
        email:"JonSmit@mail.ru",
        city:"Tokyo"
    },
    {
        id:4,
        name:"Gevorg",
        lastname:"Eranosyan",
        age:32,
        email:"GevorgEranosyan@mail.ru",
        city:"Erevan"
    },
    
]